### PR TITLE
set the actionable property False --> True to make it the default

### PR DESCRIPTION
**Pull request by PM5544**
This does what I expect it to do right? It should be the implementation that resolves issue FEED-87. Considering my knowledge of the internals (or lack thereof) I'm not 100% sure...

### CODE REVIEW

**Comment by TomOffringa** [comment]
The frontend doesn't know about this default answer, so this change does not set the default radio button choice to 'yet' in the frontend.

**Comment by PM5544** [comment]
The way I read it was that the frontend always reads the value from the data that is returned by the API, so I assumed it was part of a data structure that was set by the backend when creating feedback objects. 
But this does not result in the situation where the checkbox is ticked?

**Comment by TomOffringa** [comment]
I look wrongly, it does set the default answer according to the API! Ship it!

**Comment by PM5544** [comment]
\o/

**Pull request merged**
