### PR TITLE
Feature/docker frontend fix

### PR DESCRIPTION
**Pull request by hbokh**
- New frontend image based on node:8-slim (v8.9.3) and yarn. All modules INSIDE the image.
- The README.rst now includes the Flindt-logo

### CODE REVIEW

**Review by redmerloen — APPROVED** [review]

**Review by TomOffringa — COMMENTED** [review]
Why yarn? Why a bash script instead of RUN yarn start

**Comment by hbokh** [comment]
@TomOffringa I found this site https://www.peterbe.com/plog/how-to-create-react-app-with-docker and since there is a `yarn.lock` in our code I gave it a try.
Feel free to improve. :)

**Comment by hbokh** [comment]
**Possible bonus**: the bash-script lets you build the static-site from within the frontend-folder:
`docker container run -it -v $(pwd):/src flindt_frontend build`

**Comment by hbokh** [comment]
@TomOffringa Testing `RUN yarn start`, it keeps the build state running indefinitely, not finishing with an image. The bash-script deals with this.

**Comment by hbokh** [comment]
**TO Y'ALL**
I have dropped the previous Yarn-based Docker-image and instead used a Docker multi-stage build image that first builds the frontend with Yarn and next runs webserver nginx, serving the static frontend files.
The result is an amazingly small **26.4MB** image!

**Review by ferdynice — APPROVED** [review]

**Review by PM5544 — CHANGES_REQUESTED** [review]
Looking good! The only remark is (like we just discussed) the local node_modules folder which screws up the build when copied over to the image. When that folder is blacklisted so it isn't copied over it will help us during our development cycle a lot.

**Comment by ferdynice** [comment]
Side note for my approve: There must still be some changes to also make sure this image works for dev-purposes, now it seems a production image, because you copy the entire source.

**Comment by PM5544** [comment]
Did some digging into the new situation and NPM and Yarn should be completely interchangeable. 

For the frontend development cycle it is beneficiary to run the frontend project locally, not inside a container, or at least have the nginx inside the container transparently proxy request to the local environment. but this has the added down-side that at least the ports need to be different.

**Review by TomOffringa — APPROVED** [review]
Don't see any weird things, so safe enough to try I'd say!

**Comment by hbokh** [comment]
Closed because we've chosen another option that seems to be more developer-friendly in the long run and not making use of a static container.

**Pull request closed without merging**
